source "https://rubygems.org"

# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem "ca_legislation", :git => "git://github.com/tsyaeger/CA_legislature.git"

# Specify your gem's dependencies in ca_legislation.gemspec
gemspec
